[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = AV_Spex
version = 0.1.0
description = A Python project written for NMAAHC media conservation lab
long_description = file: README.md
long_description_content_type = text/markdown
author = Eddy Colloton
author_email = eddy.colloton@gmail.com
license = GNU v3
license_file = LICENSE
url = "https://github.com/JPC-AV/JPC_AV_videoQC"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU v3 License",
]

packages = find:
include_package_data = true

[tool.setuptools.scripts]
process-av = "AV_Spex.process_av:main"

[project]
dependencies = [
    "PyYAML==6.0.1",
    "colorlog==6.7.0",
    "art==6.1"
]
