outputs:
##  'yes' or 'no'
  access_file: 'no'
  report: 'yes'
  fixity:
    check_fixity: 'yes'
    check_stream_fixity: 'yes'
    embed_stream_fixity: 'no'
    output_fixity: 'no'
    overwrite_stream_fixity: 'no'
# preferred qctools extension. qct-parse requires qctools.xml.gz
  qctools_ext: qctools.xml.gz
tools:
  exiftool:
##  'yes' or 'no'
    check_exiftool: 'yes'
    run_exiftool: 'no'
  ffprobe:
##  'yes' or 'no'
    check_ffprobe: 'yes'
    run_ffprobe: 'no'
  mediaconch:
##  mediaconch policy file name from any xml file in the config directory
    mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
##  'yes' or 'no'
    run_mediaconch: 'yes'
  mediainfo:
##  'yes' or 'no'
    check_mediainfo: 'yes'
    run_mediainfo: 'no'
  qctools:
##  'yes' or 'no'
    check_qctools: 'yes'
    run_qctools: 'yes'
  qct-parse:
##  barsDetection can be true or left empty (null)
    barsDetection: true
##  evaluateBars can be true or left empty (null)
    evaluateBars: true
##  choose a profile from the list from config.yaml in the qct-parse[content] section
## 'contentFilter' format:
##  - allBlack
    contentFilter:
##  choose a profile from the list from config.yaml in the qct-parse[profiles] section
    profile:
##  choose a tag from the list from config.yaml in the qct-parse[fullTagList] section
## 'tagname' format:
##  - [YMIN, lt, 100] 
    tagname:
    thumbExport: true
