---
log_level: 'DEBUG'
tools:
  mediaconch: 
    run_mediaconch: 'yes'
    mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
  exiftool:
    run_exiftool: 'yes'
    check_exiftool: 'yes'
  mediainfo: 
    run_mediainfo: 'yes'
    check_mediainfo: 'yes'
  ffprobe: 
    run_ffprobe: 'yes'
    check_ffprobe: 'yes'
  qctools: 
    run_qctools: 'no'
    check_qctools: 'yes' # not implemented yet
outputs:
  difference_csv: 'no'
  qctools_ext: 'qctools.xml.gz'