---
outputs:
  access_file: 'no'
  difference_csv: 'no'
  fixity:
    check_fixity: 'no'
    check_stream_fixity: 'no'
    embed_stream_fixity: 'no'
    output_fixity: 'no'
    overwrite_stream_fixity: 'no'
  qctools_ext: qctools.xml.gz
tools:
  exiftool:
    check_exiftool: 'no'
    run_exiftool: 'no'
  ffprobe:
    check_ffprobe: 'no'
    run_ffprobe: 'no'
  mediaconch:
    mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
    run_mediaconch: 'no'
  mediainfo:
    check_mediainfo: 'no'
    run_mediainfo: 'no'
  qctools:
    check_qctools: 'yes'
    run_qctools: 'no'
  qct-parse:
    tagname: 
    over: 
    under: 
    profile: default
    buffSize:
    thumbExport: true
    thumbExportDelay: 9000
    thumbExportPath: '/Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_01663/JPC_AV_01663_qc_metadata/thumbs/'
    durationStart: 0
    durationEnd: 99999999
    barsDetection: false
    print: false
    quiet: false
