---
outputs:
  access_file: 'yes'
  difference_csv: 'yes'
  fixity:
    check_fixity: 'no'
    check_stream_fixity: 'no'
    embed_stream_fixity: 'yes'
    output_fixity: 'yes'
    overwrite_stream_fixity: 'no'
  qctools_ext: qctools.xml.gz
tools:
  exiftool:
    check_exiftool: 'yes'
    run_exiftool: 'yes'
  ffprobe:
    check_ffprobe: 'no'
    run_ffprobe: 'yes'
  mediaconch:
    mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
    run_mediaconch: 'yes'
  mediainfo:
    check_mediainfo: 'yes'
    run_mediainfo: 'yes'
  qct-parse:
    barsDetection: null
    contentFilter: null
    detectContent: null
    evaluateBars: null
    profile: null
    tagname: null
    thumbExport: null
    thumbExportDelay: null
  qctools:
    check_qctools: 'no'
    run_qctools: 'no'
