---
log_level: DEBUG
outputs:
  access_file: 'yes'
  difference_csv: 'yes'
  fixity:
    check_fixity: 'no'
    check_stream_fixity: 'no'
    embed_stream_fixity: 'yes'
    output_fixity: 'yes'
  qctools_ext: qctools.xml.gz
tools:
  exiftool:
    check_exiftool: 'yes'
    run_exiftool: 'yes'
  ffprobe:
    check_ffprobe: 'yes'
    run_ffprobe: 'yes'
  mediaconch:
    mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
    run_mediaconch: 'yes'
  mediainfo:
    check_mediainfo: 'yes'
    run_mediainfo: 'yes'
  qctools:
    check_qctools: 'no'
    run_qctools: 'no'
