mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
filename_values:
  Collection: JPC
  MediaType: AV
  ObjectID: \d{3}_\d{1}[a-zA-Z]
  DigitalGeneration: null
  FileExtension: mkv
mediainfo_values:
  expected_general:
    File extension: mkv
    Format: Matroska
    Overall bit rate mode: Variable
  expected_video:
    Format: FFV1
    Format settings  GOP: N=1
    Codec ID: V_MS/VFW/FOURCC / FFV1
    Width: 720 pixels
    Height: 486 pixels
    Pixel aspect ratio: '0.900'
    Display aspect ratio: '4:3'
    Frame rate mode: Constant
    Frame rate: '29.970'
    Standard: NTSC
    Color space: YUV
    Chroma subsampling: '4:2:2'
    Bit depth: 10 bits
    Scan type: Interlaced
    Scan order: Bottom Field First
    Compression mode: Lossless
    Color primaries: BT.601 NTSC
    colour_primaries_Source: Container
    Transfer characteristics: BT.709
    transfer_characteristics_Source: Container
    Matrix coefficients: BT.601
    MaxSlicesCount: '24'
    ErrorDetectionType: Per slice
  expected_audio:
    Format:
    - FLAC
    - PCM
    Channel(s): 2 channels
    Sampling rate: 48.0 kHz
    Bit depth: 24 bits
    Compression mode: Lossless
  expected_custom_fields:
    Title: null
    Encoded by: null
    Description: null
    Encoding settings: null
    ORIGINAL MEDIA TYPE: null
exiftool_values:
  File Type: MKV
  File Type Extension: mkv
  MIME Type: video/x-matroska
  Video Frame Rate: '29.97'
  Image Width: '720'
  Image Height: '486'
  Video Scan Type: Interlaced
  Display Width: '4'
  Display Height: '3'
  Display Unit: Display Aspect Ratio
  Codec ID:
  - A_FLAC
  - A_PCM/INT/LIT
  Audio Channels: '2'
  Audio Sample Rate: '48000'
  Audio Bits Per Sample: '24'
ffmpeg_values:
  video_stream:
    codec_name: ffv1
    codec_long_name: 'FFmpeg video codec #1'
    codec_type: video
    codec_tag_string: FFV1
    codec_tag: '0x31564646'
    width: '720'
    height: '486'
    display_aspect_ratio: '4:3'
    pix_fmt: yuv422p10le
    color_space: smpte170m
    color_transfer: bt709
    color_primaries: smpte170m
    field_order: bt
    bits_per_raw_sample: '10'
  audio_stream:
    codec_name:
    - flac
    - pcm_s24le
    codec_long_name:
    - FLAC (Free Lossless Audio Codec)
    - PCM signed 24-bit little-endian
    codec_type: audio
    codec_tag: '0x0000'
    sample_fmt: s32
    sample_rate: '48000'
    channels: '2'
    channel_layout: stereo
    bits_per_raw_sample: '24'
  format:
    format_name: matroska webm
    format_long_name: Matroska / WebM
    tags:
      creation_time: null
      ENCODER: null
      TITLE: null
      ENCODER_SETTINGS:
        Source VTR:
        - SVO5800
        - SN 122345
        - composite
        TBC:
        - SVO5800
        - SN 122345
        - composite
        Framesync:
        - DPS575
        - SN 23456
        - SDI
        Capture Device:
        - Black Magic Ultra Jam
        - SN 34567
        - Thunderbolt
        Computer:
        - Mac Mini
        - SN 45678
        - OS 14.4
        - vrecord (2024.01.01)
        - ffmpeg
        ADC:
        - DPS575
        - SN 23456
        - SDI
      DESCRIPTION: null
      ORIGINAL MEDIA TYPE: null
      ENCODED_BY: null
