---
mediaconch_policy: JPC_AV_NTSC_MKV_2023-11-21.xml
filename_values:
  Collection: "2012_79"
  MediaType: "2"
  ObjectID: \d{3}_\d{1}[a-zA-Z]
  DigitalGeneration: PM
  FileExtension: mkv
mediainfo_values:
  expected_general: 
    File extension: mkv  
    Format: Matroska  
    Overall bit rate mode: Variable
  expected_video:
    Format: FFV1  
    Format settings  GOP: N=1  
    Codec ID: V_MS/VFW/FOURCC / FFV1  
    Width: 720 pixels  
    Height: 486 pixels  
    Pixel aspect ratio: '0.900'  
    Display aspect ratio: '4:3'  
    Frame rate mode: Constant  
    Frame rate: '29.970'
    Standard: NTSC  
    Color space: YUV  
    Chroma subsampling: '4:2:2'  
    Bit depth: 10 bits  
    Scan type: Interlaced  
    Scan order: Bottom Field First  
    Compression mode: Lossless  
    Color primaries: BT.601 NTSC  
    colour_primaries_Source: Container  
    Transfer characteristics: BT.709  
    transfer_characteristics_Source: Container  
    Matrix coefficients: BT.601  
    MaxSlicesCount: '24'  
    ErrorDetectionType: Per slice  
  expected_audio: 
    Format : [ FLAC, PCM ] 
    Channel(s): 2 channels  
    Sampling rate: 48.0 kHz  
    Bit depth: 24 bits  
    Compression mode: Lossless
  expected_custom_fields: 
    Title:   
    Encoded by:   
    Description:   
    Encoding settings:   
    ORIGINAL MEDIA TYPE :
exiftool_values:
  File Type: MKV
  File Type Extension: mkv
  MIME Type: video/x-matroska
  Video Frame Rate: '29.97'
  Image Width: '720'
  Image Height: '486'
  Video Scan Type: Interlaced
  Display Width: '4'
  Display Height: '3'
  Display Unit: Display Aspect Ratio
  Codec ID: [ A_FLAC, A_PCM/INT/LIT ]
  Audio Channels: '2'
  Audio Sample Rate: '48000'
  Audio Bits Per Sample: '24'
ffmpeg_values:
  video_stream:
    codec_name: ffv1
    codec_long_name: 'FFmpeg video codec #1'
    codec_type: video  
    codec_tag_string: FFV1  
    codec_tag: '0x31564646'  
    width: '720'
    height: '486'
    display_aspect_ratio: '4:3'  
    pix_fmt: yuv422p10le  
    color_space: smpte170m  
    color_transfer: bt709  
    color_primaries: smpte170m  
    field_order: bt  
    bits_per_raw_sample: '10'
  audio_stream: 
    codec_name: [ flac, pcm_s24le ]  
    codec_long_name: [ FLAC (Free Lossless Audio Codec), PCM signed 24-bit little-endian ]  
    codec_type: audio
    codec_tag: '0x0000'
    sample_fmt: s32  
    sample_rate: '48000'  
    channels: '2'
    channel_layout: stereo  
    bits_per_raw_sample: '24'
  format:
    format_name: matroska webm  
    format_long_name: Matroska / WebM  
    tags:
      creation_time:
      ENCODER:
      TITLE: 
      ENCODER_SETTINGS: 
        settings_1:
          O: VHS 
          C: Color 
          S: Analog
          VS: NTSC
          F: '24'
          A: '4:3'
          R: '640×480'
          T: 'Sony SVO-5800'
        settings_2:
          O: FFV1mkv 
          C: Color 
          V: Composite
          S: Analog Stereo
          F: '24' 
          A: '4:3' 
          W: 10-bit 
          R: '640×480' 
          M: YUV422p10 
          T: Blackmagic UltraStudio 4K Mini SN123456, ffmpeg vrecord; in-house
        settings_3:
          O: FFV1mkv 
          W: 10-bit, 'R640x480', MYUV422p10
          N: AJ Lawrence
      DESCRIPTION:  
      ORIGINAL MEDIA TYPE: 
      ENCODED_BY: