mediaconch_policy: JPC_AV_01709_mkv.xml
filename_values:
  Collection: JPC
  MediaType: AV
  ObjectID: \d{5}
  FileExtension: mkv
mediainfo_values:
  expected_general:
    File extension: mkv
    Format: Matroska
    Overall bit rate mode: Variable
  expected_video:
    Format: FFV1
    Format settings  GOP: N=1
    Codec ID: V_MS/VFW/FOURCC / FFV1
    Width: 720 pixels
    Height: 486 pixels
    Pixel aspect ratio: '0.900'
    Display aspect ratio: '4:3'
    Frame rate mode: Constant
    Frame rate: '29.970'
    Standard: NTSC
    Color space: YUV
    Chroma subsampling: '4:2:2'
    Bit depth: 10 bits
    Scan type: Interlaced
    Scan order: Bottom Field First
    Compression mode: Lossless
    Color primaries: BT.601 NTSC
    colour_primaries_Source: Container
    Transfer characteristics: BT.709
    transfer_characteristics_Source: Container
    Matrix coefficients: BT.601
    MaxSlicesCount: '24'
    ErrorDetectionType: Per slice
  expected_audio:
    Format:
    - FLAC
    - PCM
    Channel(s): 2 channels
    Sampling rate: 48.0 kHz
    Bit depth: 24 bits
    Compression mode: Lossless
exiftool_values:
  File Type: MKV
  File Type Extension: mkv
  MIME Type: video/x-matroska
  Video Frame Rate: '29.97'
  Image Width: '720'
  Image Height: '486'
  Video Scan Type: Interlaced
  Display Width: '4'
  Display Height: '3'
  Display Unit: Display Aspect Ratio
  Codec ID:
  - A_FLAC
  - A_PCM/INT/LIT
  Audio Channels: '2'
  Audio Sample Rate: '48000'
  Audio Bits Per Sample: '24'
ffmpeg_values:
  video_stream:
    codec_name: ffv1
    codec_long_name: 'FFmpeg video codec #1'
    codec_type: video
    codec_tag_string: FFV1
    codec_tag: '0x31564646'
    width: '720'
    height: '486'
    display_aspect_ratio: '4:3'
    pix_fmt: yuv422p10le
    color_space: smpte170m
    color_transfer: bt709
    color_primaries: smpte170m
    field_order: bt
    bits_per_raw_sample: '10'
  audio_stream:
    codec_name:
    - flac
    - pcm_s24le
    codec_long_name:
    - FLAC (Free Lossless Audio Codec)
    - PCM signed 24-bit little-endian
    codec_type: audio
    codec_tag: '0x0000'
    sample_fmt: s32
    sample_rate: '48000'
    channels: '2'
    channel_layout: stereo
    bits_per_raw_sample: '24'
  format:
    format_name: matroska webm
    format_long_name: Matroska / WebM
    tags:
      creation_time:
      ENCODER:
      TITLE:
  ##  Re: ENCODER_SETTINGS 'device fields' below:
  ##  Source VTR, TBC, Framesync, ADC, Capture Device, and Computer are required fields
  ##  Subfields under these devices should be in this format:
   #    Source VTR:
   #    - model name
   #    - serial number 
   #    - video signal type (Composite, SDI, etc.) 
   #    - audio connector type (XLR, RCA, etc.)
      ENCODER_SETTINGS:
        Source VTR:
        - SVO5800
        - SN 122345
        - composite
        TBC:
        - SVO5800
        - SN 122345
        - composite
        Framesync:
        - DPS575
        - SN 23456
        - SDI
        ADC:
        - DPS575
        - SN 23456
        - SDI
        Capture Device:
        - Black Magic Ultra Jam
        - SN 34567
        - Thunderbolt
        Computer:
        - Mac Mini
        - SN 45678
        - OS 14.4
        - vrecord (2024.01.01)
        - ffmpeg
      DESCRIPTION:
      ORIGINAL MEDIA TYPE:
      ENCODED_BY:
mediatrace:
  COLLECTION:
  TITLE:
  CATALOG_NUMBER:
  DESCRIPTION:
  DATE_DIGITIZED:
  ENCODING_SETTINGS:
  ENCODED_BY:
  ORIGINAL_MEDIA_TYPE:
  DATE_TAGGED:
  TERMS_OF_USE:
  _TECHNICAL_NOTES:
  _ORIGINAL_FPS:
qct-parse:
  content:
    silence:
      Overall_Min_level: 0.001900, lt
      Overall_Max_level: 0.001900, lt
      Overall_Mean_difference: 0.009, lt
    allBlack:
      YMAX: 300, lt
      YHIGH: 115, lt
      YLOW: 97, lt
      YMIN: 6.5, lt
    static:
      YMIN: 5, lt
      YLOW: 6, lt
      YAVG: 240, lt
      YMAX: 1018, gt
      YDIF: 260, gt
      ULOW: 325, gt
      UAVG: 509, gt
      UHIGH: 695, lt
      UMAX: 990, gt
      UDIF: 138, gt
      VMIN: 100, lt
      VLOW: 385, gt
      VAVG: 500, gt
      VHIGH: 650, lt
      VMAX: 940, gt
      VDIF: 98, gt
  profiles:
    default:
      YLOW: 64
      YHIGH: 940
      ULOW: 64
      UHIGH: 940
      VLOW: 0
      VHIGH: 1023
      SATMAX: 181.02
      TOUT: 0.009
      VREP: 0.03
    highTolerance:
      YLOW: 40
      YMAX: 1000
      UMIN: 64
      UMAX: 1000
      VMIN: 0
      VMAX: 1023
      SATMAX: 181.02
      TOUT: 0.009
      VREP: 0.03
    midTolerance:
      YLOW: 40
      YMAX: 980
      UMIN: 64
      UMAX: 980
      VMIN: 0
      VMAX: 1023
      SATMAX: 181.02
      TOUT: 0.009
      VREP: 0.03
    lowTolerance:
      YLOW: 64
      YMAX: 940
      UMIN: 64
      UMAX: 940
      VMIN: 0
      VMAX: 1023
      SATMAX: 181.02
      TOUT: 0.009
      VREP: 0.03
  fullTagList:
    YMIN:
    YLOW:
    YAVG:
    YHIGH:
    YMAX:
    UMIN:
    ULOW:
    UAVG:
    UHIGH:
    UMAX:
    VMIN:
    VLOW:
    VAVG:
    VHIGH:
    VMAX:
    SATMIN:
    SATLOW:
    SATAVG:
    SATHIGH:
    SATMAX:
    HUEMED:
    HUEAVG:
    YDIF:
    UDIF:
    VDIF:
    TOUT:
    VREP:
    BRNG:
    mse_y:
    mse_u:
    mse_v:
    mse_avg:
    psnr_y:
    psnr_u:
    psnr_v:
    psnr_avg:
    Overall_Min_level:
    Overall_Max_level:
